### PR TITLE
Main article. 

### PR DESCRIPTION
**Pull request by AbdumurodovaZulfizar**
**NYT-article**
**Microverse first project.**
It is a clone of New York Times article. In this project I have used both local and global images, icons, videos, linters. I have set up linters and corrected my mistakes that shown on it. This project based on HTML and CSS languages, and includes tags in HTML and different sectors (classes mostly used). Also includes a tags that lead to real web pages.

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @AbdumurodovaZulfizar :wave: 

It's impressive to see how well you've done considering it's your first project at Microverse 👍 👏
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] The New York Times logo embedded at the center of the navbar should have a link (`a` tag)
* [x] The `Editor's Pick` section is a little stuffy. Kindly increase the width of that section.
* [x] There's a scroll bar at the bottom of your page. You can set a max-width for your page to get rid of that.
* [x] There's a section right above the footer that is not on your webpage. See below
image



> ### "As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 2 code reviews left for this project."

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by AbdumurodovaZulfizar** [comment]
**Hello, thanks for your review**
_I have corrected my mistakes_

> Now the logo of New York Times has a <a>tag and via it, we can go to the real page

> The  width of Editors' pick has been increased to 280px

> At the moment there is no scroll bar at the bottom of the page

> I have added the missing section, but I have used local images(screenshots) because I have clicked "don't show me again" by mistake, so I had to do that, but other parts work very well, 
The purpose of this project was to improve working with position and float, also flex properties, so I think the images used locally for this section is not taken as a mistake because it looks really nice.
I look forward to your approval.

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @AbdumurodovaZulfizar      ! :wave: :wave:

#### Thank you for implementing the previously required changes. However, there are changes required for you to make in order for this project to be approved. _**Note thaat you have one more review in accordance to the [Code Review Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561).**_
- - -

### **Recommended**
**General**
- [ ] You have some typos in your readme file. Also, remove any steps in the readme that are not being implemented.


**Section Specific requirements**
- [ ] Some parts of the main content texts have fonts that are larger than what is on the page. I'll recommend using [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension tool to help with this.
- [ ] The following sections need to be revisited and fixed:
- The Theory of Inflation section( the images are broken in this section),
- The Editors' Picks (just before the footer) is missing the news title,
- The above goes for the "More in Space and Astronomy" section,
- The "Suggested newsletters" section has broken images,
- The "Most Popular" section is missing all the links to various news and in it's place are horizontal lines,
 - The footer,

 **Original** |  **Your clone**
------------ | -------------
image | image



__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by AbdumurodovaZulfizar** [comment]
Hello.
I am very glad about your review, but I am going to explain my project:
1. I have corrected my Readme.MD file
2. According to requirements it is not too important the size of the
paragraph, it can be bigger a little, but the overview the same, and the
ones which should be in small size, for example, figcaptions are small. And
it couldn't be the reason for the request
3. For these parts and also for Readme.MD file I used local images, and it
is the reason why you didn't see images, just download the full repository
and it is visible for you, I have added NYT-images file with all used
images to my repository

   - The Theory of Inflation section( the images are broken in this section)
   - The "Suggested newsletters" section has broken images

4. These parts have titles,

   - The Editors' Picks (just before the footer) is missing the news title,
   - The above goes for the "More in Space and Astronomy" section,

5. They are placed horizontally, maybe it differs from screen size but it
is the same as real one and links lead to real pages. And don't forget that
this part changes over time, when I am doing this project the most popular
news were they, and when you are reviewing they have changed on the real
article.

   - The "Most Popular" section is missing all the links to various news
   and in its place are horizontal lines

6. Come to the footer it is the same as the real one, and all links lead to
real pages, and I want to mention that the appearance of the footer changes
if you change the screen size. It is the first project and media query is
not requirement for it

Lastly, the things you write as mistakes were no requirement for this
project, and the other projects which have been done by groupmates have got
approval and they were the same with mine, also they didn't use real URL
addresses, just use # sign in place of them.
I look forward your approvall, because today is the deadline for this
project

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1: 
## Hello, @AbdumurodovaZulfizar! Excellent work. The website appears to be great. This PR is now approved. You can go ahead and merge the branch. Congratulations and good luck with your next project. 

### Regarding the broken images

You have broken images on your website because your are using bad paths. 
```
// Bad Paths
<link rel="stylesheet" href="/assets/stylesheets/main.css">
<link rel="stylesheet" href="/assets/js/bootstrap.min.js">
<img src="/imgs/myimage.png">


// Good Paths
<link rel="stylesheet" href="./assets/stylesheets/main.css">
<link rel="stylesheet" href="./assets/js/bootstrap.min.js">
<img src="./imgs/myimage.png">
```

Notice how the correct paths start with a ./ that marks the current position of the file within the project directory. Without that the browser won't know where the path to the asset should start from.

**Comment by AbdumurodovaZulfizar** [comment]
This project got Approval.

**Pull request closed without merging**
